version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore TestApp.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -r linux-x64 -o ./build_output TestApp.csproj
      - cp Procfile ./build_output
artifacts:
  files:
    - '**/*'
  base-directory: ./build_output
  discard-paths: no
